var imagesVisualisation = [
  ["Alton Towers", "visualisations/altontowers.jpg"],
  ["Attractiepark Slagharen", "visualisations/attractieparkslagharen.jpg"],
  ["Avonturenpark Hellendoorn", "visualisations/avonturenparkhellendoorn.jpg"],
  ["Bellewearde", "visualisations/bellewearde.jpg"],
  ["Blackpool Pleasure Beach", "visualisations/blackpoolpleasurebeach.jpg"],
  ["Bobbejaanland", "visualisations/bobbejaanland.jpg"],
  ["Revolution, Bobbejaanland", "visualisations/bobbejaanland-revolution.jpg"],
  ["Busch Gardens", "visualisations/buschgardens.jpg"],
  ["Carowinds", "visualisations/carowinds.jpg"],
  ["Cedar Point", "visualisations/cedarpoint.jpg"],
  [
    "Chessington World of Adventures",
    "visualisations/chessingtonworldofadventures.jpg",
  ],
  ["EPCOT", "visualisations/disneyepcot.jpg"],
  ["Disneyland", "visualisations/disneylandanaheim.jpg"],
  [
    "Oga's Cantina, Disney Parks",
    "visualisations/disneylandanaheim-ogascantina.jpg",
  ],
  [
    "(Space Mountain, Disneyland)",
    "visualisations/disneylandanaheim-spacemountain.jpg",
  ],
  ["Disneyland Paris", "visualisations/disneylandparis.jpg"],
  [
    "Adventureland, Disneyland Paris",
    "visualisations/disneylandparis-adventureland.jpg",
  ],
  [
    "Pirates of the Caribbean, Disneyland Paris",
    "visualisations/disneylandparis-adventureland.jpg",
  ],
  ["Star Tours", "visualisations/disneylandparis-startours.jpg"],
  [
    "Discoveryland, Disneyland Paris",
    "visualisations/disneylandparis-discoveryland.jpg",
  ],
  [
    "Fantasyland, Disneyland Paris",
    "visualisations/disneylandparis-fantasyland.jpg",
  ],
  [
    "Frontierland, Disneyland Paris",
    "visualisations/disneylandparis-frontierland.jpg",
  ],
  ["Phantom Manor", "visualisations/disneylandparis-phantommanor.jpg"],
  ["Magic Kingdom", "visualisations/disneymagickingdom.jpg"],
  [
    "Space Mountain, Magic Kingdom",
    "visualisations/disneymagickingdom-spacemountain.jpg",
  ],
  ["Animal Kingdom", "visualisations/disneysanimalkingdom.jpg"],
  [
    "Disney's California Adventure",
    "visualisations/disneyscaliforniaadventure.jpg",
  ],
  [
    "California Screamin' (Paradise Pier, Disney's California Adventure)",
    "visualisations/disneyscaliforniaadventure-californiascreamin.jpg",
  ],
  ["Hollywood Studios", "visualisations/disneyshollywoodstudios.jpg"],
  ["Dollywood", "visualisations/dollywood.jpg"],
  ["Efteling", "visualisations/efteling.jpg"],
  ["Energylandia", "visualisations/energylandia.jpg"],
  ["Europa-Park", "visualisations/europapark.jpg"],
  [
    "Blue Fire Megacoaster (Island, Europa-Park)",
    "visualisations/europapark-bluefire.jpg",
  ],
  [
    "Blue Fire Megacoaster, Europa-Park",
    "visualisations/europapark-bluefire.jpg",
  ],
  ["Voletarium, Europa-Park", "visualisations/europapark-voletarium.jpg"],
  ["Everland", "visualisations/everland.jpg"],
  ["Flamingo Land", "visualisations/flamingoland.jpg"],
  ["Fort Fun Abenteuerland", "visualisations/fortfunabenteuerland.jpg"],
  ["Fraispertuis City", "visualisations/fraispertuiscity.jpg"],
  ["Futuroscope", "visualisations/futuroscope.jpg"],
  [
    "Chasseurs de Tornades (Futuroscope)",
    "visualisations/futuroscope-chasseursdetornades.jpg",
  ],
  ["Hansa Park", "visualisations/hansapark.jpg"],
  ["Heide Park", "visualisations/heidepark.jpg"],
  ["Hersheypark", "visualisations/hersheypark.jpg"],
  ["Holiday Park", "visualisations/holidaypark.jpg"],
  ["Hong-Kong Disneyland", "visualisations/hongkongdisneyland.jpg"],
  ["Kings Island", "visualisations/kingsisland.jpg"],
  ["Legendia", "visualisations/legendia.jpg"],
  ["Legoland Windsor", "visualisations/legolandwindsor.jpg"],
  ["Lightwater Valley", "visualisations/lightwatervalley.jpg"],
  ["Linnanmäki", "visualisations/linnanmaki.jpg"],
  ["Liseberg", "visualisations/liseberg.jpg"],
  ["Mirabilandia", "visualisations/mirabilandia.jpg"],
  ["Movie Park Germany", "visualisations/movieparkgermany.jpg"],
  ["Nigloland", "visualisations/nigloland.jpg"],
  ["Oakwood Theme Park", "visualisations/oakwoodthemepark.jpg"],
  ["Parc Astérix", "visualisations/parcasterix.jpg"],
  ["Parc Spirou", "visualisations/parcspirou.jpg"],
  ["Paultons Park", "visualisations/paultonspark.jpg"],
  ["Phantasialand", "visualisations/phantasialand.jpg"],
  ["Chiapas, Phantasialand", "visualisations/phantasialand-chiapas.jpg"],
  ["Klugheim, Phantasialand", "visualisations/phantasialand-klugheim.jpg"],
  ["Rookburgh, Phantasialand", "visualisations/phantasialand-rookburgh.jpg"],
  ["Plopsaland de Panne", "visualisations/plopsalanddepanne.jpg"],
  [
    "The Ride to Happiness by Tomorrowland, Plopsaland de Panne",
    "visualisations/plopsalanddepanne-theridetohappiness.jpg",
  ],
  ["PortAventura World", "visualisations/portaventuraworld.jpg"],
  ["Puy du Fou", "visualisations/puydufou.jpg"],
  ["Schwaben Park", "visualisations/schwabenpark.jpg"],
  ["Shanghai Disneyland", "visualisations/shanghaidisneyland.jpg"],
  ["Silver Dollar City", "visualisations/silverdollarcity.jpg"],
  ["Six Flags", "visualisations/sixflags.jpg"],
  ["Terra Mitica", "visualisations/terramitica.jpg"],
  ["Thorpe Park", "visualisations/thorpepark.jpg"],
  ["Tibidabo", "visualisations/tibidabo.jpg"],
  ["Tokyo Disneyland", "visualisations/tokyodisneyland.jpg"],
  ["Tokyo Disney Sea", "visualisations/tokyodisneysea.jpg"],
  ["Toverland", "visualisations/toverland.jpg"],
  ["Avalon, Toverland", "visualisations/toverland-avalon.jpg"],
  ["Fēnix, Toverland", "visualisations/toverland-avalon.jpg"],
  ["Tripsdrill", "visualisations/tripsdrill.jpg"],
  ["Islands of Adventure", "visualisations/universalislandsofadventure.jpg"],
  ["Universal Studios Orlando", "visualisations/universalstudiosorlando.jpg"],
  [
    "Hollywood Rip Ride Rock it, Universal Studios Orlando",
    "visualisations/universalstudiosorlando-hollywoodripriderockit.jpg",
  ],
  [
    "Universal Studios Hollywood",
    "visualisations/universalstudioshollywood.jpg",
  ],
  ["Walibi Belgium", "visualisations/walibibelgium.jpg"],
  ["Walibi Holland", "visualisations/walibiholland.jpg"],
  ["Walt Disney Studios", "visualisations/waltdisneystudios.jpg"],
  [
    "Rock'n'Roller Coaster avec Aerosmith, Walt Disney Studios",
    "visualisations/waltdisneystudios-rocknrollercoaster.jpg",
  ],
  [
    "The Twilight Zone Tower of Terror, Walt Disney Studios",
    "visualisations/waltdisneystudios-towerofterror.jpg",
  ],

  ["MegaMix", "images/visu-megamix.jpg"],
  ["Made in Europe", "images/visu-madeineurope.jpg"],
  ["Le Monde d'IMAscore", "images/visu-mondeimascore.jpg"],
  ["America f*** Yeah !", "images/visu-americafyeah.jpg"],
  ["RetroLand", "images/visu-retroland.jpg"],
  ["OnBoard!", "images/visu-onboard.jpg"],
  ["Friday Night Fright", "images/visu-fridaynightfright.jpg"],
  ["Le Live", "images/visu-lelive.jpg"],
];
